---
title: "Lmwithpredictions"
author: "Adesuwa Mukoro"
date: "10/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
This is the linear model with prediction problem.
Predict strength scores using data from the following website. 


```{r}
dataF <- read.csv(file="http://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt",sep="",header=TRUE)
```
```{r include=FALSE}
require(tidyverse)
require(tigerstats)
require(rgl)
require(knitr)
require(ggplot)
```

###Plot scatterplot

```{r}
plot(SIMS~ARM,data=dataF)
```

```{r}
basicNN <- ggplot(dataF,aes(y=SIMS,x=ARM))
basicNN + geom_point()+ geom_smooth(method=lm)
```

## now add the model fit to our plot

```{r}
model.1 <- lm(SIMS~ARM,data=dataF)
summary.lm(model.1)
New= data.frame(grip=94,ARM=88)
predict.lm(model.1,New,interval = "prediction")
```
Model 1 fit, the adjusted r-square is 0.467. About 47% of the variability in SIMS can be explained by the variability in ARM. The predicted score for SIMS is 0.71. The 95% confidence interval is from -1.726209 to 3.138977.

